Repository indigo-dc/jenkins-pipeline-library, pull requests merged in 2020-07, with the labels that each got.

#58 Handle defaults for config:credentials
  src/eu/indigo/compose/parser/ConfigParser.groovy
  vars/pipelineConfig.groovy
Labels: enhancement

#52 How to build docs
  docs/contrib/documentation.rst
  docs/index.rst
  docs/requirements.txt
Labels: documentation

#76 Highly recommend the use of `container_name` in docker compose.
  docs/user/docker_compose.rst
  docs/user/step_by_step/sqa_criteria.rst
Labels: critical, documentation

#81 Feature/doc/run docker images as services
  docs/user/docker_compose.rst
  docs/user/step_by_step/sqa_criteria.rst
Labels: documentation

#82 getConfigSetting: removeAll java.util.Collection call
  src/eu/indigo/compose/parser/ConfigParser.groovy
Labels: bug

#86 Fix extra lines in the intro
  docs/user/step_by_step/sqa_criteria.rst
Labels: bug, documentation

#89 config::project_repos optional
  src/eu/indigo/compose/DockerCompose.groovy
  src/eu/indigo/compose/parser/ConfigParser.groovy
Labels: enhancement

#90 Add private repository support
  src/eu/indigo/compose/DockerCompose.groovy
  vars/pipelineConfig.groovy
Labels: enhancement
