Repository indigo-dc/jenkins-pipeline-library, pull requests merged in 2020-11, with the labels that each got.

#109 Allow to control debug settings and correct a bug
  src/eu/indigo/JenkinsDefinitions.groovy
  src/eu/indigo/compose/DockerCompose.groovy
Labels: bug, enhancement

#110 Feature/docker compose push
  docs/user/config_file.rst
  src/eu/indigo/JenkinsDefinitions.groovy
  src/eu/indigo/compose/DockerCompose.groovy
Labels: bug, documentation, enhancement

#111 LocalBranch support and add scm package
  .github/workflows/jenkins.yml
  src/eu/indigo/compose/DockerCompose.groovy
  src/eu/indigo/scm/Git.groovy
  src/eu/indigo/scm/GitLocalBranch.groovy
  vars/pipelineConfig.groovy
Labels: enhancement

#107 Use LocalBranch class to avoid the default detached HEAD status
  .github/workflows/jenkins.yml
  src/eu/indigo/scm/Git.groovy
  src/eu/indigo/scm/GitLocalBranch.groovy
  vars/pipelineConfig.groovy
Labels: critical, enhancement
